a=pip2 b=install
$a $b  aenum
$a $b  attrs
$a $b  backports.functools-lru-cache
$a $b  certifi
$a $b  chardet
$a $b  Click
$a $b  fbbot
$a $b  fbchat
$a $b  html5lib
$a $b  idna
$a $b  mechanize
$a $b  pip
$a $b  requests
$a $b  setuptools
$a $b  six
$a $b  soupsieve
$a $b  spark-parser
$a $b  uncompyle2
$a $b  uncompyle6
$a $b  urllib3
$a $b  webencodings
$a $b  xdis
